# Generated by Django 4.1.3 on 2022-12-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_snack_calcium_snack_calories_snack_carbohydrate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serving_size', models.CharField(default=0, max_length=5)),
                ('total_content', models.CharField(default=0, max_length=5)),
                ('calories', models.CharField(default=0, max_length=5)),
                ('protein', models.CharField(default=0, max_length=5)),
                ('fat', models.CharField(default=0, max_length=5)),
                ('carbohydrate', models.CharField(default=0, max_length=5)),
                ('sugars', models.CharField(default=0, max_length=5)),
                ('dietary_fiber', models.CharField(default=0, max_length=5)),
                ('calcium', models.CharField(default=0, max_length=5)),
                ('iron', models.CharField(default=0, max_length=5)),
                ('potassium', models.CharField(default=0, max_length=5)),
                ('sodium', models.CharField(default=0, max_length=5)),
                ('vitamin', models.CharField(default=0, max_length=5)),
                ('cholesterol', models.CharField(default=0, max_length=5)),
                ('total_fat', models.CharField(default=0, max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='snack',
            name='calcium',
        ),
        migrations.RemoveField(
            model_name='snack',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='snack',
            name='carbohydrate',
        ),
        migrations.RemoveField(
            model_name='snack',
            name='cholesterol',
        ),
        migrations.RemoveField(
            model_name='snack',
            name='dietary_fiber',
        ),
        migrations.RemoveField(
            model_name='snack',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='snack',
            name='iron',
        ),
        migrations.RemoveField(
            model_name='snack',
            name='potassium',
        ),
        migrations.RemoveField(
            model_name='snack',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='snack',
            name='serving_size',
        ),
        migrations.RemoveField(
            model_name='snack',
            name='sodium',
        ),
        migrations.RemoveField(
            model_name='snack',
            name='sugars',
        ),
        migrations.RemoveField(
            model_name='snack',
            name='total_content',
        ),
        migrations.RemoveField(
            model_name='snack',
            name='total_fat',
        ),
        migrations.RemoveField(
            model_name='snack',
            name='vitamin',
        ),
    ]
