# Generated by Django 4.1.3 on 2022-12-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_nutrition_remove_snack_calcium_remove_snack_calories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrition',
            name='name',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
