# Generated by Django 4.1.3 on 2022-12-02 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_nutrition_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.snack'),
        ),
    ]
