# Generated by Django 4.1.3 on 2022-12-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_nutrition_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='name',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
