# Generated by Django 4.1.3 on 2022-12-02 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_nutrition_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nutrition',
        ),
    ]
