# Generated by Django 4.1.3 on 2022-12-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_nutrition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='calcium',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='calories',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='carbohydrate',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='cholesterol',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='dietary_fiber',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='fat',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='iron',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='potassium',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='protein',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='serving_size',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='sodium',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='sugars',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='total_content',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='total_fat',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='vitamin',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
