# Generated by Django 4.1.3 on 2022-12-02 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_nutrition_calcium_alter_nutrition_calories_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nutrition',
        ),
    ]
