# Generated by Django 4.1.3 on 2022-12-02 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_nutrition'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nutrition',
        ),
    ]
